pipeline {
    agent any

    stages {
        stage('Pull image') {
            steps {
                echo 'Updating docker image'
                sh 'docker pull papajool/big_data_lab2:latest'
            }
        }
        
        stage('Run container') {
            steps {
                sh 'curl https://raw.githubusercontent.com/PapaJool/big_data_lab2/main/docker-compose.yml -o docker-compose.yml'
                sh 'dir'
                sh 'docker compose up'
            }
        }
    }
    post {
        always {
            sh 'docker compose down'
        }
    }
}
