pipeline {
    agent any

    stages {
        stage('Pull image') {
            steps {
                echo 'Updating docker image'
                sh 'docker pull papajool/big_data_lab2:latest'
            }
        }

        stage('Prepare environment') {
            steps {
                sh 'sudo rm -r -f *'
                sh 'echo "CLICKHOUSE_HOST=0.0.0.0" >> .env'
                sh 'echo "CLICKHOUSE_PORT=8123" >> .env'
                sh 'echo "CLICKHOUSE_USER=${CLICKHOUSE_CREDS_USR}" >> .env'
                sh 'echo "CLICKHOUSE_PASSWORD=${CLICKHOUSE_CREDS_PSW}" >> .env'
                 }
            }

        stage('Run container') {
            steps {
                sh 'curl https://raw.githubusercontent.com/PapaJool/big_data_lab2/main/docker-compose.yml -o docker-compose.yml'
                sh 'dir'
                sh 'docker compose up'
            }
        }
    }
    post {
        always {
            sh 'docker compose down'
            sh 'docker logout'
        }
    }
}
