pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('big_data_lab2')
        CLICKHOUSE_CREDS=credentials('click_house')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Clone github repository') {
            steps {
                cleanWs()
                sh 'git clone -b main https://github.com/PapaJool/big_data_lab2'
				}
			}

		stage('Prepare environment') {
            steps {
                sh 'echo "CLICKHOUSE_HOST=0.0.0.0" >> .env'
                sh 'echo "CLICKHOUSE_PORT=8123" >> .env'
                sh 'echo "CLICKHOUSE_USER=${CLICKHOUSE_CREDS_USR}" >> .env'
                sh 'echo "CLICKHOUSE_PASSWORD=${CLICKHOUSE_CREDS_PSW}" >> .env'
                 }
            }

        stage('Checkout repo dir') {
            steps {
                sh 'cd big_data_lab2 && dir'
				}
			}

        stage('Login'){
            steps{
                //withCredentials([usernamePassword(credentialsId: 'mle-template', passwordVariable: 'DOCKER_REGISTRY_PWD', usernameVariable: 'DOCKER_REGISTRY_USER')]){
                //sh 'echo $DOCKER_REGISTRY_PWD | docker login -u $DOCKER_REGISTRY_USER --password-stdin'}
                //sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
                }
            }

        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        sh 'cd big_data_lab2 && docker compose build'
                        }

                    finally {
                    sh '''
                        cd big_data_lab2
                        docker compose up -d
                        '''
                        }
				    }
                }
            }

        stage('Checkout coverage report'){
            steps{
                dir("big_data_lab2"){
                    sh '''
                    docker compose logs -t --tail 10
                    '''
                }
            }
        }

        stage('Push'){
            steps{
                sh 'docker push papajool/big_data_lab2:latest'
            }
        }
	    
		
	}

    post {
        always {
            //sh 'docker compose -f big_data_lab2/docker-compose.yml down'
            sh 'docker logout'
        }
    }
}
