pipeline {
    agent any
    
    environment {
        DOCKERHUB_CREDS=credentials('mle-template')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    stages {
        stage('Cloning repo') {
            steps {
                echo 'Cloning repo'
                sh 'rd /s /q my-mle-template 2>null'
                sh 'git clone https://github.com/PapaJool/mle-template.git'
                sh 'cd my-mle-template'
            }
        }
        
        stage('Building docker') {
            steps {
                dir("my-mle-template") {
                    sh 'docker login -u papajool -p %DH_CREDS_PSW% docker.io'
                    sh 'docker-compose build'
                }
            }
        }
        stage('Run docker') {
            steps {
                dir("my-mle-template") {
                    sh 'docker-compose up'
                    sh 'docker-compose logs -t --tail 10'
                }
            }
        }
        stage('Push to DockerHub') {
            steps {
                dir("my-mle-template") {
                    sh 'docker push papajool/mle-template:latest'
                }
            }
        }
    }
    post {
        always {
            dir("my-mle-template") {
                sh 'docker-compose down 2>null'
                sh 'docker logout'
            }
        }
    }
}
